telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1c5f8>: Failed to establish a new connection: [Errno 61] Connection refused',)': /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1c320>: Failed to establish a new connection: [Errno 61] Connection refused',)': /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1c908>: Failed to establish a new connection: [Errno 61] Connection refused',)': /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1c9e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1c4a8>: Failed to establish a new connection: [Errno 61] Connection refused',)': /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1cc88>: Failed to establish a new connection: [Errno 61] Connection refused',)': /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1cd30>: Failed to establish a new connection: [Errno 61] Connection refused',)': /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot728852231:AAEZLnITK0BYNpAfQ4DCIC8CjpyiYLYUpIo/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x106a1ce48>: Failed to establish a new connection: [Errno 61] Connection refused',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
